// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HelperDate is an autogenerated mock type for the HelperDate type
type HelperDate struct {
	mock.Mock
}

// CompareDate provides a mock function with given fields: date
func (_m *HelperDate) CompareDate(date string) error {
	ret := _m.Called(date)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyCancelDate provides a mock function with given fields: date
func (_m *HelperDate) VerifyCancelDate(date string) error {
	ret := _m.Called(date)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHelperDate creates a new instance of HelperDate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
