name: Docker Image CI

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-music-studio:latest
      -  
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop ${{ secrets.CONTAINER_NAME }}
            docker rm ${{ secrets.CONTAINER_NAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/go-music-studio
            docker run --name ${{ secrets.CONTAINER_NAME }} -p 8080:8080 -d -e SECRET=${{ secrets.SECRET }} -e ProjectID=${{ secrets.PROJECTID }} -e DatabaseURL=${{ secrets.DATABASEURL }} -e GOOCREDS=${{ secrets.GOOCREDS }} -e MidtransSandBoxServerKey=${{ secrets.MIDTRANSSANDBOXSERVERKEY }} -e MidtransSandBoxClientKey=${{ secrets.MIDTRANSSANDBOXCLIENTKEY }} ${{ secrets.DOCKERHUB_USERNAME }}/go-music-studio
